export const SET_LOADING = 'SET_LOADING';
export const TOTAL_CASES = 'TOTAL_CASES';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const SPECIFIC_COUNTRY = 'SPECIFIC_COUNTRY';
export const COUNTRY_DETAILS = 'COUNTRY_DETAILS';
export const ALL_COUNTRIES = 'ALL_COUNTRIES';
export const ALL_CONTINENTS = 'ALL_CONTINENTS';
export const CONTINENT_DETAILS = 'CONTINENT_DETAILS';